{
    'name': 'Tremos Custom Reports',
    'version': '16.0.1.0.0',
    'summary': 'Custom reports',
    'description': """This custom module to hundle custom reportings""",
    'category': 'Generic Modules',
    'author': "Trend Motives Solutions",
    'company': 'Trend Motives Solutions',
    'maintainer': 'BroadSpace Interactive',
    'website': "https://husseinkadweka.com",
    'depends': ['base','account','product'],
    'data': ['security/ir.model.access.xml','reports/invoice_report.xml','views/account_views.xml'],
    'images': ['static/description/logo.jpeg'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
