name: Push & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy With Latest Code
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          username: ${{secrets.SSH_USERNAME}} # User of the server you want to ssh into
          password: ${{secrets.SSH_PASSWORD}} # SSH server user password
          port: ${{secrets.SSH_PORT}} # SSH server port
          script_stop: true # Will stop build incase of any failures
          script: |
            cd /home/odoo/odoo
            git pull origin main
            docker build -t alandick:odoo-15.0 .
            docker-compose down
            docker-compose up -d
            docker system prune -f
